import AppDataSource from "../config/db-config";
import { Hotel } from "./entities/hotel.entity";
import { Room } from "./entities/room.entity";
import { Member } from "./entities/member.entity";
import { CreateHotelDto, CreateRoomDto, CreateMemberDto, UpdateHotelDto, UpdateRoomDto, UpdateMemberDto } from "./dto/trip.dto";
import { ApiResponse } from "../common/helper/api-success.helper";
import { ApiError } from "../common/helper/api-error.helper";
import { statusCode } from "../common/messages/status-code.messages";
import * as fs from "fs";
import * as path from "path";

export class TripService {
    private hotelRepository = AppDataSource.getRepository(Hotel);
    private roomRepository = AppDataSource.getRepository(Room);
    private memberRepository = AppDataSource.getRepository(Member);

    async createHotel(data: CreateHotelDto): Promise<ApiResponse<Hotel>> {
        const hotel = this.hotelRepository.create(data);
        await this.hotelRepository.save(hotel);
        return new ApiResponse(statusCode.Created, hotel, "Hotel created successfully");
    }

    async createRoom(data: CreateRoomDto): Promise<ApiResponse<Room>> {
        const hotel = await this.hotelRepository.findOneBy({ id: data.hotelId });
        if (!hotel) {
            throw new ApiError(statusCode.NotFound, "Hotel not found");
        }

        const room = this.roomRepository.create({
            roomNumber: data.roomNumber,
            floor: data.floor,
            groupType: data.groupType,
            hotel: hotel
        });
        await this.roomRepository.save(room);
        return new ApiResponse(statusCode.Created, room, "Room created successfully");
    }

    async createMember(data: CreateMemberDto): Promise<ApiResponse<Member>> {
        const room = await this.roomRepository.findOneBy({ id: data.roomId });
        if (!room) {
            throw new ApiError(statusCode.NotFound, "Room not found");
        }

        let imageUrl = "";
        if (data.image) {
            const baseUrl = process.env.BASE_URL || `http://localhost:${process.env.PORT || 3000}`;
            // data.image now contains the filename generated by multer
            imageUrl = `${baseUrl}/Uploads/${data.image}`;
        }

        const member = this.memberRepository.create({
            name: data.name,
            role: data.role,
            isLead: data.isLead || false,
            image: imageUrl || undefined,
            contactInfo: data.contactInfo,
            description: data.description,
            room: room
        });
        await this.memberRepository.save(member);
        return new ApiResponse(statusCode.Created, member, "Member created successfully");
    }

    async getTrips(): Promise<ApiResponse<any>> {
        const hotels = await this.hotelRepository.find({
            relations: ["rooms", "rooms.members"],
            order: {
                id: "DESC"
            }
        });

        // Map to group.json heavily nested structure
        const formattedHotels = hotels.map(hotel => {
            return {
                hotelName: hotel.hotelName,
                checkin: hotel.checkin || "",
                checkout: hotel.checkout || "",
                teamDirectory: hotel.rooms.map(room => {
                    // Create formatted title (e.g. TRAVEL_LEAD to Travel Lead)
                    const tempTitle = room.groupType.replace(/_/g, ' ').toLowerCase();
                    const formattedTitle = tempTitle.split(' ').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');

                    return {
                        groupType: room.groupType,
                        title: formattedTitle,
                        room: {
                            number: String(room.roomNumber),
                            floor: String(room.floor),
                            label: `Room ${room.roomNumber} · ${room.floor}${room.floor === 1 ? 'st' : room.floor === 2 ? 'nd' : room.floor === 3 ? 'rd' : 'th'} Floor`
                        },
                        members: room.members.map(member => ({
                            id: `usr-${String(member.id).padStart(3, '0')}`,
                            isLead: member.isLead,
                            image: member.image || "",
                            name: member.name,
                            role: member.role,
                            contactInfo: member.contactInfo,
                            description: member.description || ""
                        }))
                    };
                })
            };
        });

        return new ApiResponse(statusCode.OK, formattedHotels, "Trips retrieved successfully");
    }

    async updateHotel(id: number, data: UpdateHotelDto): Promise<ApiResponse<Hotel>> {
        const hotel = await this.hotelRepository.findOneBy({ id });
        if (!hotel) throw new ApiError(statusCode.NotFound, "Hotel not found");

        Object.assign(hotel, data);
        await this.hotelRepository.save(hotel);
        return new ApiResponse(statusCode.OK, hotel, "Hotel updated successfully");
    }

    async deleteHotel(id: number): Promise<ApiResponse<null>> {
        const result = await this.hotelRepository.delete({ id });
        if (result.affected === 0) throw new ApiError(statusCode.NotFound, "Hotel not found");
        return new ApiResponse(statusCode.OK, null, "Hotel deleted successfully");
    }

    async updateRoom(id: number, data: UpdateRoomDto): Promise<ApiResponse<Room>> {
        const room = await this.roomRepository.findOneBy({ id });
        if (!room) throw new ApiError(statusCode.NotFound, "Room not found");

        if (data.hotelId) {
            const hotel = await this.hotelRepository.findOneBy({ id: data.hotelId });
            if (!hotel) throw new ApiError(statusCode.NotFound, "Hotel not found");
            room.hotel = hotel;
        }

        Object.assign(room, data);
        await this.roomRepository.save(room);
        return new ApiResponse(statusCode.OK, room, "Room updated successfully");
    }

    async deleteRoom(id: number): Promise<ApiResponse<null>> {
        const result = await this.roomRepository.delete({ id });
        if (result.affected === 0) throw new ApiError(statusCode.NotFound, "Room not found");
        return new ApiResponse(statusCode.OK, null, "Room deleted successfully");
    }

    async updateMember(id: number, data: UpdateMemberDto): Promise<ApiResponse<Member>> {
        const member = await this.memberRepository.findOneBy({ id });
        if (!member) throw new ApiError(statusCode.NotFound, "Member not found");

        if (data.roomId) {
            const room = await this.roomRepository.findOneBy({ id: data.roomId });
            if (!room) throw new ApiError(statusCode.NotFound, "Room not found");
            member.room = room;
        }

        if (data.image) {
            const baseUrl = process.env.BASE_URL || `http://localhost:${process.env.PORT || 3000}`;
            member.image = `${baseUrl}/Uploads/${data.image}`;
        }

        if (data.name !== undefined) member.name = data.name;
        if (data.role !== undefined) member.role = data.role;
        if (data.isLead !== undefined) member.isLead = data.isLead;
        if (data.contactInfo !== undefined) member.contactInfo = data.contactInfo;
        if (data.description !== undefined) member.description = data.description;

        await this.memberRepository.save(member);
        return new ApiResponse(statusCode.OK, member, "Member updated successfully");
    }

    async deleteMember(id: number): Promise<ApiResponse<null>> {
        const result = await this.memberRepository.delete({ id });
        if (result.affected === 0) throw new ApiError(statusCode.NotFound, "Member not found");
        return new ApiResponse(statusCode.OK, null, "Member deleted successfully");
    }

    async deleteAllTrips(): Promise<ApiResponse<null>> {
        // Clearing hotels cascades down to rooms and members because of the CASCADE configuration
        await this.hotelRepository.clear();
        return new ApiResponse(statusCode.OK, null, "All trips permanently deleted successfully");
    }
}
